vissim:
  file-path: "E:\\JAVALearn\\VariableSpeedLimit\\vissim\\LaneClose\\"
  file-name: "laneclose"

simulation:
  simulation-time: 100
  resolution: 1
  speed: 1
  random-seed: 4
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/constructionarea?useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true